name: e2e
on:
  push:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "24.1.0"

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install
        run: |
          pnpm install
          npx playwright install --with-deps

      - name: build
        run: pnpm storybook:build

      - name: run server
        run: |
          python -m http.server 6006 --directory "${{ github.workspace }}/storybook-static" &

      - name: e2e test
        run: pnpm e2e:ci

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results
